[package]
name = "wasm"
version = "0.1.0"
authors = ["stoically <stoically@protonmail.com>"]
edition = "2018"

# Config mostly pulled from: https://github.com/rustwasm/wasm-bindgen/blob/master/examples/fetch/Cargo.toml

[lib]
crate-type = ["cdylib"]

[dependencies]
url = "2.2.2"
wasm-bindgen = { version = "0.2.74", features = ["serde-serialize"] }
wasm-bindgen-futures = "0.4.24"
console_error_panic_hook = "0.1.6"
web-sys = { version = "0.3.51", features = ["console"] }

[dependencies.matrix-sdk]
path = "../.."
default-features = false
features = ["native-tls", "encryption", "indexeddb-state-store", "indexeddb-crypto-store"]

[workspace]

[dev-dependencies]
wasm-bindgen-test = "0.3.29"
