[package]
name = "matrix-sdk-integration-testing"
description = "Internal integration testing for matrix-sdk crate"
version = "0.1.0"
edition = "2021"
publish = false

[dev-dependencies]
anyhow = "1"
assign = "1"
lazy_static = "1.4"
matrix-sdk = { path = "../../crates/matrix-sdk" }
tempfile = "3.3.0"
tokio = { version = "1", features = ["rt", "rt-multi-thread", "macros"] }
