language: rust
rust: stable
addons:
  apt:
    packages:
      - libssl-dev

cache: cargo

jobs:
  include:
    - os: linux
      dist: bionic

    - os: osx
    - os: linux
      name: Coverage
      before_script:
          - cargo install cargo-tarpaulin
      script:
          - cargo tarpaulin --features 'encryption sqlite-cryptostore' -v
      after_success:
          - cargo tarpaulin --out Xml
          - bash <(curl -s https://codecov.io/bash)

before_script:
  - rustup component add rustfmt

script:
  - cargo build  --no-default-features --features 'encryption sqlite-cryptostore'
  - cargo fmt --all -- --check
  - cargo test --no-default-features --features 'encryption sqlite-cryptostore'
