[workspace]
members = [
    "crates/matrix-sdk",
    "crates/matrix-qrcode",
    "crates/matrix-sdk-base",
    "crates/matrix-sdk-test",
    "crates/matrix-sdk-test-macros",
    "crates/matrix-sdk-crypto",
    "crates/matrix-sdk-common",
    "crates/matrix-sdk-appservice"
]
