[workspace]
members = [
    "crates/matrix_sdk",
    "crates/matrix_qrcode",
    "crates/matrix_sdk_base",
    "crates/matrix_sdk_test",
    "crates/matrix_sdk_test_macros",
    "crates/matrix_sdk_crypto",
    "crates/matrix_sdk_common",
    "crates/matrix_sdk_appservice"
]
