[package]
authors = ["Damir Jelić <poljar@termina.org.uk"]
description = "A high level Matrix client-server library."
edition = "2018"
homepage = "https://github.com/matrix-org/matrix-rust-sdk"
keywords = ["matrix", "chat", "messaging", "ruma", "nio"]
license = "Apache-2.0"
name = "matrix-sdk"
readme = "README.md"
repository = "https://github.com/matrix-org/matrix-rust-sdk"
version = "0.1.0"

[features]
default = []
encryption = ["olm-rs", "serde/derive", "serde_json", "cjson"]
sqlite-cryptostore = ["sqlx", "zeroize"]

[dependencies]
futures = "0.3.4"
reqwest = "0.10.4"
http = "0.2.1"
url = "2.1.1"
async-trait = "0.1.26"


# Ruma dependencies
js_int = "0.1.3"
ruma-api = "0.15.0-dev.1"
ruma-client-api = { git = "https://github.com/matrix-org/ruma-client-api/", version = "0.6.0" }
ruma-events = { git = "https://github.com/matrix-org/ruma-events", version = "0.17.0" }
ruma-identifiers = "0.14.1"

# Dependencies for the encryption support
olm-rs = { git = "https://gitlab.gnome.org/poljar/olm-rs", optional = true, features = ["serde"]}
serde = { version = "1.0.105", optional = true, features = ["derive"] }
serde_json = { version = "1.0.49", optional = true }
cjson = { version = "0.1.0", optional = true }
zeroize = { version = "1.1.0", optional = true }

# Misc dependencies
thiserror = "1.0.13"
tracing = "0.1.13"

[dependencies.tracing-futures]
version = "0.2.3"
default-features = false
features = ["std", "std-future"]

[dependencies.tokio]
version = "0.2.13"
default-features = false
features = ["sync", "time"]

[dependencies.sqlx]
version = "0.3.2"
optional = true
default-features = false
features = ["runtime-tokio", "sqlite"]

[dev-dependencies]
tokio = { version = "0.2.13", features = ["rt-threaded", "macros"] }
tracing-subscriber = "0.2.3"
tempfile = "3.1.0"
mockito = "0.23.3"

