coverage:
  status:
    project:
      default:
        # by default, we only care about test coverage of the main
        # rust crates
        target: auto
        threshold: 1%
        paths:
          - "crates"
      bindings:
        # Coverage of binding tests is recorded but for informational
        # purposes only
        informational: true
        paths:
          - "bindings"
      labs:
        # Coverage of lab tests is recorded but for informational
        # purposes only
        informational: true
        paths:
          - "labs"
    patch: off
