coverage:
  status:
    project:
      default:
        # by default, we only care about test coverage of the main
        # rust crates
        target: auto
        threshold: 1%
        paths:
          - "crates"
      bindings:
        # Coverage of binding tests is recorded but for informational
        # purposes only
        informational: true
        paths:
          - "bindings"
      labs:
        # Coverage of lab tests is recorded but for informational
        # purposes only
        informational: true
        paths:
          - "labs"
    patch:
      default:
        # Be tolerant on slight code coverage diff on PRs to limit
        # noisy red coverage status on github PRs.
        # Note: The coverage stats are still uploaded
        # to codecov so that PR reviewers can see uncovered lines
        target: auto
        threshold: 1%
