[default-config]
debug = false
verbose = false
exclude-files = ["crates/matrix_sdk/examples/*", "crates/matrix_sdk_common", "crates/matrix_sdk_test"]
exclude = ["matrix-sdk-crypto-js", "matrix-sdk-crypto-nodejs"]
