[default-config]
debug = false
verbose = false
exclude-files = ["crates/matrix_sdk/examples/*"]
exclude = [
    "matrix-sdk-common",
    "matrix-sdk-test",
    "matrix-sdk-indexeddb",
    "matrix-sdk-crypto-ffi",
    "matrix-sdk-crypto-js",
    "matrix-sdk-crypto-nodejs"
]
