[package]
name = "matrix-sdk-bwi"
version = "0.1.0"
edition = "2021"
rust-version.workspace = true

[features]
uniffi = ["dep:uniffi"]

[dependencies]
mockall = "0.13.0"
regex = "1.10.5"
serde = { version = "1.0.151", features = ["derive"] }
serde_json = "1.0.91"
reqwest = { version = "0.12.9", features = ["json", "rustls-tls"], default-features = false }
tokio = { version = "1.38.1", features = ["full"] }
uniffi = { workspace = true, optional = true }
thiserror = "1.0.63"
anyhow = "1.0.86"
url = "2.5.2"

[lints]
workspace = true
