[package]
name = "matrix-sdk-bwi"
version = "0.1.1"
edition = "2021"
rust-version.workspace = true

[features]
uniffi = ["dep:uniffi"]

[dependencies]
serde = { version = "1.0.151", features = ["derive"] }
serde_json = "1.0.91"
reqwest = { workspace = true, features = ["json"] }
tokio = { workspace = true, features = ["macros"] }
uniffi = { workspace = true, optional = true }
anyhow = "1.0.86"
url = "2.5.2"
zxcvbn = { workspace = true }

[lints]
workspace = true
