[package]
name = "matrix-sdk-bwi"
version = "0.1.0"
edition = "2021"
rust-version.workspace = true

[features]
uniffi = ["dep:uniffi"]

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
reqwest = { workspace = true, features = ["json"] }
tokio = { workspace = true, features = ["macros"] }
uniffi = { workspace = true, optional = true }
anyhow = { workspace = true }
url = { workspace = true }
zxcvbn = { workspace = true }

[dev-dependencies]
rusty-hook = "0.11.2"

[lints]
workspace = true
