[package]
name = "matrix-sdk-bwi"
version = "0.2.0"
edition = "2021"
rust-version.workspace = true

[dependencies]
anyhow = { workspace = true }
serde = { workspace = true, features = ["derive"] }
reqwest = { workspace = true, features = ["json"] }
tokio = { workspace = true, features = ["macros"] }
url = { workspace = true }
zxcvbn = "3.1.0"
serde_json = "1.0.135"

[dev-dependencies]
rusty-hook = "0.11.2"

[lints]
workspace = true
