[package]
name = "matrix-sdk-base-bwi"
version = "0.1.0"
edition = "2021"
rust-version.workspace = true

[dependencies]
mockall = "0.13.0"
regex = "1.10.5"
serde = { version = "1.0.151" }
serde_json = "1.0.91"


[lints]
workspace = true
