[package]
name = "matrix-sdk-indexeddb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
matrix-sdk-base = { path = "../matrix-sdk-base", features = ["state_key"] }
matrix-sdk-crypto = { path = "../matrix-sdk-crypto" }
matrix-sdk-common = { path = "../matrix-sdk-common" }
thiserror = "1.0.25"
anyhow = "1"

indexed_db_futures = { version = "0.2.0" }
wasm-bindgen = { version = "0.2.74", features = ["serde-serialize"] }
serde = { version = "1.0.126" }
serde_json = "1.0.64"
dashmap = "4.0.2"

[dev-dependencies]
matrix-sdk-base = {  path = "../matrix-sdk-base", features = ["testing"] }
matrix-sdk-crypto = { path = "../matrix-sdk-crypto", features = ["testing"] }
matrix-sdk-test = { path = "../matrix-sdk-test" }
wasm-bindgen-test = "0.3.24"