[package]
name = "matrix-sdk-indexeddb"
version = "0.1.0"
edition = "2021"

[features]
default = ["encryption"]
encryption = ["matrix-sdk-crypto"]


[dependencies]
matrix-sdk-base = { path = "../matrix-sdk-base", features = ["state_key"] }
matrix-sdk-crypto = { path = "../matrix-sdk-crypto", optional = true }
matrix-sdk-common = { path = "../matrix-sdk-common" }
thiserror = "1.0.25"
anyhow = "1"

futures-util = { version = "0.3.15", default-features = false }
indexed_db_futures = { version = "0.2.0" }
wasm-bindgen = { version = "0.2.74", features = ["serde-serialize"] }
serde = { version = "1.0.126" }
serde_json = "1.0.64"
dashmap = "4.0.2"
tracing = "0.1.26"

[dev-dependencies]
matrix-sdk-base = {  path = "../matrix-sdk-base", features = ["testing"] }
matrix-sdk-crypto = { path = "../matrix-sdk-crypto", features = ["testing"] }
matrix-sdk-test = { path = "../matrix-sdk-test" }
wasm-bindgen-test = "0.3.24"