[package]
name = "matrix-qrcode"
description = "Library to encode and decode QR codes for interactive verifications in Matrix land"
version = "0.2.0"
authors = ["Damir Jelić <poljar@termina.org.uk>"]
edition = "2021"
homepage = "https://github.com/matrix-org/matrix-rust-sdk"
keywords = ["matrix", "chat", "messaging", "ruma", "nio"]
license = "Apache-2.0"
readme = "README.md"
rust-version = "1.56"
repository = "https://github.com/matrix-org/matrix-rust-sdk"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = ["decode_image"]
decode_image = ["image", "rqrr", "qrcode/image", "qrcode/svg"]

[dependencies]
base64 = "0.13.0"
byteorder = "1.4.3"
image = { version = "0.23.14", optional = true }
qrcode = { version = "0.12.0", default-features = false }
rqrr = { version = "0.4.0", optional = true }
thiserror = "1.0.25"

[dependencies.ruma-identifiers]
git = "https://github.com/ruma/ruma/"
rev = "b9f32bc6327542d382d4eb42ec43623495c50e66"

[dependencies.ruma-serde]
git = "https://github.com/ruma/ruma/"
rev = "b9f32bc6327542d382d4eb42ec43623495c50e66"
