[package]
name = "media_content-scanner"
version = "0.1.0"
edition = "2021"
rust-version.workspace = true

[dependencies]
anyhow = "1"
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tracing-subscriber = "0.3.15"
url = { workspace = true }
# when copy-pasting this, please use a git dependency or make sure that you
# have copied the example as it was at the time of the release you use.
matrix-sdk = { path = "../../crates/matrix-sdk", features = ["sso-login"] }

[lints]
workspace = true
