[package]
authors = ["Damir Jelić <poljar@termina.org.uk"]
description = "A high level Matrix client-server library."
edition = "2018"
homepage = "https://github.com/matrix-org/matrix-rust-sdk"
keywords = ["matrix", "chat", "messaging", "ruma", "nio"]
license = "Apache-2.0"
name = "matrix-sdk"
readme = "README.md"
repository = "https://github.com/matrix-org/matrix-rust-sdk"
version = "0.1.0"

[features]
default = ["encryption", "sqlite-cryptostore"]
encryption = ["matrix-sdk-crypto"]
sqlite-cryptostore = ["matrix-sdk-crypto/sqlite-cryptostore"]

[dependencies]
dirs = "2.0.2"
futures = "0.3.4"
reqwest = "0.10.4"
http = "0.2.1"
url = "2.1.1"
async-trait = "0.1.30"
serde = "1.0.106"
serde_json = "1.0.51"
uuid = { version = "0.8.1", features = ["v4"] }

matrix-sdk-types = { path = "../matrix_sdk_types" }
matrix-sdk-crypto = { path = "../matrix_sdk_crypto", optional = true }

# Misc dependencies
thiserror = "1.0.14"
tracing = "0.1.13"
atomic = "0.4.5"
dashmap = "3.10.0"

[dependencies.tracing-futures]
version = "0.2.3"
default-features = false
features = ["std", "std-future"]

[dependencies.tokio]
version = "0.2.16"
default-features = false
features = ["sync", "time", "fs"]

[dependencies.sqlx]
version = "0.3.3"
optional = true
default-features = false
features = ["runtime-tokio", "sqlite"]

[dev-dependencies]
tokio = { version = "0.2.16", features = ["rt-threaded", "macros"] }
ruma-identifiers = { version = "0.16.0", features = ["rand"] }
serde_json = "1.0.51"
tracing-subscriber = "0.2.4"
tempfile = "3.1.0"
mockito = "0.25.1"
lazy_static = "1.4.0"
