[package]
authors = ["Damir Jelić <poljar@termina.org.uk>"]
description = "A high level Matrix client-server library."
edition = "2018"
homepage = "https://github.com/matrix-org/matrix-rust-sdk"
keywords = ["matrix", "chat", "messaging", "ruma", "nio"]
license = "Apache-2.0"
name = "matrix-sdk"
readme = "README.md"
repository = "https://github.com/matrix-org/matrix-rust-sdk"
version = "0.1.0"

[package.metadata.docs.rs]
features = ["docs"]
rustdoc-args = ["--cfg", "feature=\"docs\""]

[features]
default = ["encryption", "sqlite_cryptostore", "messages", "native-tls"]

messages = ["matrix-sdk-base/messages"]
encryption = ["matrix-sdk-base/encryption", "dashmap"]
sqlite_cryptostore = ["matrix-sdk-base/sqlite_cryptostore"]
native-tls = ["reqwest/native-tls"]
rustls-tls = ["reqwest/rustls-tls"]

docs = ["encryption", "sqlite_cryptostore", "messages"]

[dependencies]
async-trait = "0.1.38"
dashmap = { version = "3.11.10", optional = true }
http = "0.2.1"
serde_json = "1.0.57"
thiserror = "1.0.20"
tracing = "0.1.19"
url = "2.1.1"

matrix-sdk-common-macros = { version = "0.1.0", path = "../matrix_sdk_common_macros" }
matrix-sdk-common = { version = "0.1.0", path = "../matrix_sdk_common" }

[dependencies.matrix-sdk-base]
version = "0.1.0"
path = "../matrix_sdk_base"
default_features = false

# FIXME: Revert to regular dependency once 0.10.8 or 0.11.0 is released
[dependencies.reqwest]
git = "https://github.com/seanmonstar/reqwest"
rev = "cff487ff58630cf0ac59f3e46cbf20cf50a28b3f"
default_features = false

[dependencies.tracing-futures]
version = "0.2.4"
default-features = false
features = ["std", "std-future"]

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
futures-timer = "3.0.2"

[target.'cfg(target_arch = "wasm32")'.dependencies.futures-timer]
version = "3.0.2"
features = ["wasm-bindgen"]

[dev-dependencies]
async-trait = "0.1.38"
dirs = "3.0.1"
matrix-sdk-test = { version = "0.1.0", path = "../matrix_sdk_test" }
tokio = { version = "0.2.22", features = ["rt-threaded", "macros"] }
serde_json = "1.0.57"
tracing-subscriber = "0.2.11"
tempfile = "3.1.0"
mockito = "0.27.0"
lazy_static = "1.4.0"
futures = "0.3.5"

[[example]]
name = "emoji_verification"
required-features = ["encryption"]
