[alias]
xtask = "run --package xtask --"

[doc.extern-map.registries]
crates-io = "https://docs.rs/"

[target.'cfg(all())']
rustflags = [
    "-Wrust_2018_idioms",
    "-Wsemicolon_in_expressions_from_macros",
    "-Wunused_extern_crates",
    "-Wunused_import_braces",
    "-Wunused_qualifications",
    "-Wtrivial_casts",
    "-Wtrivial_numeric_casts",
    "-Wclippy::cloned_instead_of_copied",
    "-Wclippy::dbg_macro",
    "-Wclippy::inefficient_to_string",
    "-Wclippy::macro_use_imports",
    "-Wclippy::mut_mut",
    "-Wclippy::needless_borrow",
    "-Wclippy::nonstandard_macro_braces",
    "-Wclippy::str_to_string",
    "-Wclippy::todo",
]
