[package]
authors = ["Damir Jelić <poljar@termina.org.uk"]
description = "Matrix encryption library"
edition = "2018"
homepage = "https://github.com/matrix-org/matrix-rust-sdk"
keywords = ["matrix", "chat", "messaging", "ruma", "nio"]
license = "Apache-2.0"
name = "matrix-sdk-crypto"
readme = "README.md"
repository = "https://github.com/matrix-org/matrix-rust-sdk"
version = "0.1.0"

[features]
default = []
sqlite-cryptostore = ["sqlx"]

[dependencies]
async-trait = "0.1.30"

matrix-sdk-common = { version = "0.1.0", path = "../matrix_sdk_common" }

olm-rs = { version = "0.5.0", features = ["serde"] }
serde = { version = "1.0.106", features = ["derive"] }
serde_json = "1.0.52"
cjson = { git = "https://github.com/stoically/cjson", rev = "24a82d94e339e27a62434493869f3dce62c60e0d" }
zeroize = { version = "1.1.0", features = ["zeroize_derive"] }
url = "2.1.1"

# Misc dependencies
thiserror = "1.0.16"
tracing = "0.1.13"
atomic = "0.4.5"
dashmap = "3.11.1"

[dependencies.tracing-futures]
version = "0.2.4"
default-features = false
features = ["std", "std-future"]

[target.'cfg(not(target_arch = "wasm32"))'.dependencies.sqlx]
version = "0.3.5"
optional = true
default-features = false
features = ["runtime-tokio", "sqlite"]

[dev-dependencies]
tokio = { version = "0.2.20", features = ["rt-threaded", "macros"] }
ruma-identifiers = { version = "0.16.1", features = ["rand"] }
serde_json = "1.0.52"
tempfile = "3.1.0"
http = "0.2.1"
