[package]
name = "matrix-sdk-bwi-test"
version = "0.1.0"
edition = "2021"
rust-version.workspace = true

[dependencies]
matrix-sdk-base = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
wiremock = { workspace = true }

[lints]
workspace = true
