[package]
authors = ["Damir Jelić <poljar@termina.org.uk>"]
description = "The base component to build a Matrix client library."
edition = "2021"
homepage = "https://github.com/matrix-org/matrix-rust-sdk"
keywords = ["matrix", "chat", "messaging", "ruma", "nio"]
license = "Apache-2.0"
name = "matrix-sdk-base"
readme = "README.md"
repository = "https://github.com/matrix-org/matrix-rust-sdk"
rust-version = "1.56"
version = "0.4.1"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = []
encryption = ["matrix-sdk-crypto", "state_key"]
qrcode = ["matrix-sdk-crypto/qrcode"]

# State Key is a helper feature for state store implementations
state_key = [
    "pbkdf2",
    "hmac",
    "sha2",
    "rand",
    "chacha20poly1305",
]
# helpers for testing features build upon this
testing = [ ]

[dependencies]
chacha20poly1305 = { version = "0.9.0", optional = true }
dashmap = "4.0.2"
futures-core = "0.3.15"
futures-util = { version = "0.3.15", default-features = false }
hmac = { version = "0.12.0", optional = true }
lru = "0.7.2"
matrix-sdk-common = { version = "0.4.0", path = "../matrix-sdk-common" }
matrix-sdk-crypto = { version = "0.4.0", path = "../matrix-sdk-crypto", optional = true }
pbkdf2 = { version = "0.10.0", default-features = false, optional = true }
rand = { version = "0.8.4", optional = true }
serde = { version = "1.0.126", features = ["rc"] }
serde_json = "1.0.64"
sha2 = { version = "0.10.1", optional = true }
thiserror = "1.0.25"
tracing = "0.1.26"
zeroize = { version = "1.3.0", features = ["zeroize_derive"] }
anyhow = "1"

[dependencies.ruma]
git = "https://github.com/ruma/ruma/"
rev = "b9f32bc6327542d382d4eb42ec43623495c50e66"
features = ["client-api-c"]

[dev-dependencies]
futures = { version = "0.3.15", default-features = false, features = ["executor"] }
http = "0.2.4"
matrix-sdk-test = { version = "0.4.0", path = "../matrix-sdk-test" }