name: Appservice

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

env:
  CARGO_TERM_COLOR: always

jobs:
  test-appservice:
    if: github.event_name == 'push' || !github.event.pull_request.draft
    name: ${{ matrix.os }} / appservice / stable

    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu, macOS]

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Load cache
        uses: Swatinem/rust-cache@v1

      - name: Run checks
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: -p xtask -- ci test-appservice
