name: Lint

on:
  push:
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all --check

    - uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: --all-targets -- -D warnings
