name: WASM

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  check-wasm:
    name: Build test
    runs-on: ubuntu-latest

    strategy:
#      fail-fast: true

      matrix:
        name:
          - matrix-qrcode
          - matrix-sdk (no-default, wasm-flags)
          - matrix-sdk-base
          - matrix-sdk-common
          - matrix-sdk-crypto
          - matrix-sdk-base / indexeddb_state_store
          - matrix-sdk-crypto / indexeddb_cryptostore

        include:
          - name: matrix-qrcode
            cargo_args: --package matrix-qrcode
          - name: matrix-sdk (no-default, wasm-flags)
            cargo_args: --no-default-features --features qrcode,encryption,indexeddb_stores,rustls-tls --package matrix-sdk
          - name: matrix-sdk-base
            cargo_args: --package matrix-sdk-base
          - name: matrix-sdk-common
            cargo_args: --package matrix-sdk-common
          - name: matrix-sdk-crypto
            cargo_args: --package matrix-sdk-crypto

          # special check for specific features
          - name: matrix-sdk-base / indexeddb_state_store
            cargo_args: --package matrix-sdk-base --features indexeddb_state_store
          - name: matrix-sdk-crypto / indexeddb_cryptostore
            cargo_args: --package matrix-sdk-crypto --features indexeddb_cryptostore

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: wasm32-unknown-unknown
        profile: minimal
        override: true

    - name: Load cache
      uses: Swatinem/rust-cache@v1

    # needed for libolm-sys compilation
    - name: Install emscripten
      uses: mymindstorm/setup-emsdk@v11
      with:
        version: ${{ matrix.emcc_version || 'latest'  }}

    - name: check
      uses: actions-rs/cargo@v1
      with:
        command: check
        args: --target wasm32-unknown-unknown ${{ matrix.cargo_args }}

  test-wasm:
    # building wasm is not enough, we've seen runtime errors before,
    # hence the tests
    name: ${{ matrix.name }} test
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}

    strategy:
      matrix:
        include:
          - name: "matrix-sdk-crypto @Node14 emcc2.0"
            experimental: false
            emcc_version: 2.0.27
            base_dir: matrix-sdk-crypto
            cargo_args: --features indexeddb_cryptostore
          - name: matrix-sdk-base
            experimental: false
            base_dir: matrix-sdk-base
            cargo_args: --features indexeddb_state_store,indexeddb_cryptostore
          - name: matrix-sdk
            experimental: false
            base_dir: matrix-sdk
            # FIXME: we have to skip all examples b/c of https://github.com/rustwasm/wasm-pack/issues/666
            cargo_args:  --no-default-features --features indexeddb_stores,rustls-tls --lib
          - name: "matrix-sdk-example-wasm_command_bot @Node14"
            experimental: false
            emcc_version: 2.0.27
            node_version: '14'
            # known to work
            base_dir: matrix-sdk/examples/wasm_command_bot
            cmd: |
              npm install
              npm test
              wasm-pack test --firefox --headless

          # these are _known_ broken on latest node
          # - name: matrix-sdk-crypto
          #   experimental: true
          #   base_dir: matrix-sdk-crypto
          - name: matrix-sdk-example-wasm_command_bot
            base_dir: matrix-sdk/examples/wasm_command_bot
            # this might fail
            experimental: true
            cmd: |
              npm install
              npm test
              wasm-pack test --firefox --headless

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: wasm32-unknown-unknown
        profile: minimal
        override: true

    - name: Load cache
      uses: Swatinem/rust-cache@v1

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node_version || 'lts/*' }}

    - name: Install emscripten
      uses: mymindstorm/setup-emsdk@v11
      with:
        version: ${{ matrix.emcc_version || 'latest'  }}

    - name: Install wasm-pack
      run: cargo install wasm-pack

    - name: Verify versions
      run: |
        echo "> node --version"
        node --version
        echo "> npm --version"
        npm --version
        echo "> wasm-pack --version"
        wasm-pack --version
        echo "> emcc -v"
        emcc -v

    - name: Default wasm-pack tests
      if: ${{!matrix.cmd}}
      run: |
        cd crates/${{matrix.base_dir}}
        wasm-pack test --node -- ${{ matrix.cargo_args }}
        wasm-pack test --firefox --headless -- --features ${{ matrix.cargo_args }}

    - name: Testing with custom command
      if: ${{matrix.cmd}}
      run: |
        cd crates/${{matrix.base_dir}}
        ${{matrix.cmd}}
