name: WASM

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

env:
  CARGO_TERM_COLOR: always

jobs:
  check-wasm:
    name: Build test / ${{ matrix.name }}
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || !github.event.pull_request.draft

    strategy:
      fail-fast: true
      matrix:
        name:
          - matrix-sdk-qrcode
          - matrix-sdk-base
          - matrix-sdk-common
          - matrix-sdk-crypto-js
          - indexeddb-no-crypto
          - indexeddb-with-crypto

        include:
          - name: matrix-sdk (no-default, wasm-flags)
            cmd: matrix-sdk-no-default
          - name: matrix-sdk / indexeddb_stores
            cmd: matrix-sdk-indexeddb-stores
          - name: matrix-sdk / indexeddb_stores / no crypto
            cmd: matrix-sdk-indexeddb-stores-no-crypto
          - name: matrix-sdk / wasm-example
            cmd: matrix-sdk-command-bot

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: wasm32-unknown-unknown
        components: clippy
        profile: minimal
        override: true

    - name: Install wasm-pack
      uses: jetli/wasm-pack-action@v0.3.0
      with:
        version: 'latest'

    - name: Load cache
      uses: Swatinem/rust-cache@v1

    - name: Rust Check
      uses: actions-rs/cargo@v1
      with:
        command: run
        args: -p xtask -- ci wasm ${{ matrix.cmd || matrix.name }}

    - name: Wasm-Pack test
      uses: actions-rs/cargo@v1
      with:
        command: run
        args: -p xtask -- ci wasm-pack ${{ matrix.cmd || matrix.name }}
